version: '3'

services:
  blockchain-minor-redis:
    container_name: blockchain-minor-redis
    image: redis:5.0
    volumes:
      - ./blockchain-minor-redis:/data:cached
    ports:
      - 6379:6379
  blockchain-minor-mongodb:
    container_name: blockchain-minor-mongodb
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - ./blockchain-minor-mongodb:/data:cached
    ports:
      - 27017:27017
    working_dir: /var/lib/mongodb
